#!/bin/bash

if [[ -e dependencies ]]; then
    exit 0
fi

set -e

#avoid to download all boost libs
#git clone --recursive https://github.com/arangodb/fuerte.git

mkdir -p dependencies

git clone https://github.com/arangodb/velocypack.git dependencies/velocypack 
git clone https://github.com/arangodb/fuerte.git dependencies/fuerte
